### PR TITLE
Make commands more modular.

### PR DESCRIPTION
**Pull request by ghost**
Whilst not being as automated as #2, this PR allows for more ranks or functions for verification system, as you said you wanted to have a verification system in time, with this version allowing for that more than the other does.

### CODE REVIEW

**Comment by Kefta** [comment]
This is really messy and wasteful IMO, but I guess it's up to personal style. You should definitely squash your commits, though.

**Comment by ghost** [comment]
I agree with squashing, but I don't normally use git so worked on my master branch instead.

On the style, the way I've worked allows for expansion in the future, considering that Coal stated that they wanted a "verification system" which my PR allows for, whilst the authentication for yours is currently only based upon IsAdmin checks.

A midpoint between the two styles would be nice however, considering that yours is a lot simpler to read compared to mine.

**Comment by Kefta** [comment]
I believe the verification system is what he had before instead of an IsAdmin check

**Comment by ghost** [comment]
I thought that was a password system, and he was changing it to have a verification system, since the thread says 

> [The password system is only temporary until I can get a working verification system]

I mean, if we could get @DerpyCoal here to clarify, that would be best.

**Pull request closed without merging**
